### ISSUE TITLE
Installation failed in `gvm` environment

### ISSUE THREAD

**Issue by MaiLunJiye** [ray-x/go.nvim#437] opened 2024-03-08 02:37 UTC
![image](https://github.com/ray-x/go.nvim/assets/20548127/cd52a0b8-24c8-4c0a-8de6-5ca520b010b1)

config:

```
    {
        "ray-x/go.nvim",
        dependencies = {  -- optional packages
            "ray-x/guihua.lua",
            "neovim/nvim-lspconfig",
            "nvim-treesitter/nvim-treesitter"
        },
        config = function()
            require("go").setup()
        end,
        event = {"CmdlineEnter"},
        ft = {"go", 'gomod'},
        build = ':lua require("go.install").update_all_sync()' -- if you need to install/update all binaries
    },

```

gvm :

```
Go Version Manager v1.0.22 installed at /home/xxxxxx/.gvm
```

![image](https://github.com/ray-x/go.nvim/assets/20548127/cc311322-a275-499f-8736-8ee3da0b9c03)
![image](https://github.com/ray-x/go.nvim/assets/20548127/0dce4e47-bffa-4534-82da-ac00f1f02f33)
![image](https://github.com/ray-x/go.nvim/assets/20548127/3bfca219-811d-4df4-8a32-e2e5b509c981)

**Comment by ray-x** [comment] 2024-03-10 09:19
ATM only the latest version of go tools will be installed. From the error log, the issue is go1.19 does not compile golangci latest version (which reference slices) 
I think you might need to switch to a more recent go version to install the tools. After that, you can switch back to 1.19.

**Closed** 2024-03-29 06:15 UTC
